## Build settings
locale: "pt-BR"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

## Site Settings
title: CallMarx
author:
  name             : "Eugenio Augusto Jimenes"
  avatar           : "assets/eu-e-nila.webp"
  bio              : >-
    Nerd, dislexico, esquerdopata convicto, viciado-hipster em café,
    desenvolvedor e linux fanboy.
  location         : "São Paulo - SP"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:eugeniojimenes@gmail"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/callmarx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eugenio-augusto-jimenes/"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/callmarx"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eugenio-augusto-jimenes/"

# Analytics
analytics:
  provider               : false
  google:
    tracking_id          :
    anonymize_ip         :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .github
  - .rubocop.yml
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - config
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
words_per_minute: 100
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "<!-- excerpt-separator -->"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Sao_Paulo
date_format: "%Y-%m-%d"

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
      show_date: true
