name: deploy generated site to GitHub Pages on gh-branch 

on:
  # Triggers the workflow on push requests if the commit includes a tag that matches the Semantic Version release tag
  push:
    tags: releases/\d+\.\d+\.\d+ # yep, the conditional is a regular expression. Modify the RegExp if the release tags in your site use a different format
    branches: [ main ]
  # This line allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy-site-to-github-pages"
  deploy-site-to-github-pages:
     # The type of runner that the job will run on
    runs-on: ubuntu-latest  # ToDo: investigate if a specific ubuntu is better

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the main repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # Both of these fine OSS actions will do the job. 
    # I keep both in here, but one commented out, in case I find in the future that only one or the other has a feature I might need

    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@4.1.1
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: ./_site # The folder the action should deploy.
      
    # Deploys a source to a destination.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site # the action will deploy the <repository root>/_site contents to the (default) gh-pages branch, root directory
